apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: llm-test
  name: llm-test
  annotations: {}
spec:
  selector:
    matchLabels:
      app: llm-test
  replicas: 1
  template:
    metadata:
      labels:
        app: llm-test
    spec:
      nodeName: node0
      containers:
        - name: llm-test
          image: llm-train
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c", "--"]
          args: ["while true; do sleep 30; done;"]
          # torchrun --nnodes 2 --nproc_per_node 2 --rdzv-id=123 --rdzv-backend=c10d --rdzv-endpoint=llm-test.llm-test.svc.cluster.local:29500 --local_addr llm-test.llm-test.svc.cluster.local finetuning.py --enable_fsdp --quantization False --use_fp16 True --fsdp_config.optimizer SGD --split_slice 1%
          resources:
            limits:
              nvidia.com/gpu: 4
            requests:
              cpu: 500m
              memory: 16Gi
              nvidia.com/gpu: 4

---

apiVersion: v1
kind: Service
metadata:
  namespace: llm-test
  name: llm-test
spec:
  clusterIP: None
  ports:
    - name: c10d
      port: 29500
      protocol: TCP
  selector:
    app: llm-test